name: audiobookshelf
services:
  audiobookshelf:
    environment:
      PGID: $PGID
      PUID: $PUID
      TZ: $TZ
    image: advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    deploy:
      resources:
        reservations:
          memory: "256M"
    network_mode: server
    ports:
      - target: 80
        published: "13378"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/audiobookshelf/config
        target: /config
      - type: bind
        source: /DATA/AppData/audiobookshelf/metadata
        target: /metadata  
      - type: bind
        source: /DATA/Media/Audiobooks
        target: /audiobooks
    x-casaos:
      envs:
        - container: TZ
          description:
            en_us: TimeZone
            zh_cn: 时区
        - container: PUID
          description:
            en_us: Run Audiobookshelf as specified uid.
            zh_cn: 以指定的uid运行Radarr
        - container: PGID
          description:
            en_us: Run Audiobookshelf as specified gid.
            zh_cn: 以指定的gid运行Radarr
      ports:
        - container: "13378"
          description:
            en_us: WebUI HTTP Port
            zh_cn: WebUI HTTP端口

      volumes:
        - container: /config
          description:
            en_us: Audiobookshelf config directory.
            zh_cn: Audiobookshelf配置目录
        - container: /audiobooks
          description:
            en_us: Audiobooks movies directory.
            zh_cn: Audiobooks电影目录
        - container: /metadata
          description:
            en_us: Audiobookshelf metadata directory.
            zh_cn: Audiobookshelf下载目录
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: audiobookshelf
  author: advplyr
  category: Media
  description:
    en_us: Audiobookshelf Features - Fully open-source, including the android & iOS app (in beta). Stream all audio formats on the fly. Search and add podcasts to download episodes with auto-download. Multi-user support with custom permissions. Keeps progress per user and syncs across devices. Auto-detects library updates, no need to re-scan. Upload books and podcasts w/ bulk upload drag and drop folders. Backup your metadata plus automated daily backups. Progressive Web App (PWA). Chromecast support on the web app and android app. Fetch metadata and cover art from several sources. Chapter editor and chapter lookup (using Audnexus API). Merge your audio files into a single m4b. Embed metadata and cover image into your audio files (using Tone). Basic ebook support and e-reader (experimental).
  developer: advplyr
  icon: https://cdn.jsdelivr.net/gh/garlik82/CasaOS-AppStore@main/Apps/Audiobookshelf/icon-2.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/garlik82/CasaOS-AppStore@main/Apps/Audiobookshelf/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/garlik82/CasaOS-AppStore@main/Apps/Audiobookshelf/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/garlik82/CasaOS-AppStore@main/Apps/Audiobookshelf/screenshot-3.png
  tagline:
    en_us: Audiobookshelf is a self-hosted audiobook and podcast server.
  thumbnail: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Radarr/thumbnail.jpg
  tips: {Android App (beta) Try it out on the Google Play Store  iOS App (early beta) - Available using Test Flight: https://testflight.apple.com/join/wiic7QIW}
  title:
    en_us: Audiobookshelf
  index: /
  port_map: "13378"
